"""
Application-wide constants
"""

# Legacy constants for compatibility
SAFETY_CONFIDENCE_THRESHOLD = 0.8
CRISIS_DETECTION_THRESHOLD = 0.9
PROFANITY_WARNING_THRESHOLD = 0.7
MAX_MESSAGE_LENGTH = 2000
MIN_MESSAGE_LENGTH = 2
MAX_CONTEXT_SIZE = 5000
RATE_LIMIT_REQUESTS = 10
RATE_LIMIT_WINDOW = 60
RATE_LIMIT_WINDOW_SECONDS = 60
MAX_CONVERSATION_HISTORY = 100
RECENT_HISTORY_LIMIT = 10
MAX_PERSONAS_LOAD = 100
CHAT_HISTORY_DISPLAY_LIMIT = 20
NON_COMPLIANT_DEFAULT_TEMPERATURE = 0.8
MOTIVATIONAL_COACH_DEFAULT_TEMPERATURE = 0.6
THERAPEUTIC_ASSISTANT_DEFAULT_TEMPERATURE = 0.5

class ConversationConstants:
    """Constants related to conversation handling"""
    MAX_HISTORY_LENGTH = 10
    DEFAULT_CONFIDENCE = 0.85
    MIN_CONFIDENCE = 0.0
    MAX_CONFIDENCE = 1.0
    RECENT_HISTORY_LIMIT = 10
    MAX_CONVERSATION_HISTORY = 100

class TokenConstants:
    """Constants related to token handling"""
    CHAR_TO_TOKEN_RATIO = 4
    MIN_TOKENS = 1
    MAX_TOKENS = 4000
    DEFAULT_MAX_TOKENS = 500

class SafetyConstants:
    """Constants for safety monitoring"""
    CRISIS_INTERVENTION_CONFIDENCE = 1.0
    SAFETY_CHECK_LAST_N_MESSAGES = 5
    SAFETY_INTERVENTION_THRESHOLD = 0.6

class APIConstants:
    """API-related constants"""
    MAX_RETRIES = 3
    RETRY_DELAY_BASE = 1  # seconds
    DEFAULT_PAGE_SIZE = 20
    MAX_PAGE_SIZE = 100

class PersonaConstants:
    """Persona-related constants"""
    MIN_DIFFICULTY_LEVEL = 1
    MAX_DIFFICULTY_LEVEL = 10
    DEFAULT_DIFFICULTY_LEVEL = 5
    MIN_TEMPERATURE = 0.0
    MAX_TEMPERATURE = 2.0
    DEFAULT_TEMPERATURE = 0.7
