-- ===================================================================
-- SUPABASE INSPECTION QUERIES
-- Run these manually in your Supabase SQL Editor
-- ===================================================================

-- 1. VIEW ALL PERSONA TEMPLATES
-- This shows the personas that should be available in the chat
SELECT
    id,
    persona_seed,
    status,
    metadata,
    created_at
FROM conversations
WHERE status = 'template'
ORDER BY created_at;

-- 2. VIEW ACTIVE CONVERSATIONS
-- Shows any ongoing conversations
SELECT
    id,
    persona_seed,
    status,
    created_at,
    metadata
FROM conversations
WHERE status = 'active'
ORDER BY created_at DESC;

-- 3. VIEW MI ANALYSIS RESULTS
-- Shows the quality of MI techniques being used
SELECT
    conversation_id,
    turn_number,
    user_message,
    technique_detected,
    quality_score,
    empathy_score,
    neutrality_maintained,
    resistance_triggered,
    created_at
FROM mi_analysis
ORDER BY created_at DESC;

-- 4. VIEW PERSONA RESPONSES (if any)
-- Shows what responses were generated by the AI
SELECT
    conversation_id,
    response_text,
    depth_level,
    instruction_used,
    emotional_tone
FROM persona_responses
ORDER BY conversation_id;

-- 5. CHECK LEGACY TABLES
-- See if there's old data interfering
SELECT COUNT(*) as persona_count FROM personas;
SELECT COUNT(*) as messages_count FROM messages;

-- 6. DETAILED VIEW OF MARY'S PERSONA SEED
-- See exactly what Mary should be acting like
SELECT
    persona_seed,
    metadata
FROM conversations
WHERE persona_seed LIKE 'Mary%'
AND status = 'template';

-- ===================================================================
-- DIAGNOSTIC QUERIES
-- ===================================================================

-- 7. CHECK IF FRONTEND IS CALLING API
-- Look for any recent API usage
SELECT
    COUNT(*) as total_conversations,
    COUNT(CASE WHEN status = 'active' THEN 1 END) as active_conversations,
    COUNT(CASE WHEN status = 'template' THEN 1 END) as templates
FROM conversations;

-- 8. VIEW QUALITY PATTERNS
-- See the MI analysis patterns
SELECT
    conversation_id,
    sustained_empathy,
    recent_resistance,
    depth_achieved,
    avg_quality_score,
    total_turns
FROM quality_patterns
ORDER BY updated_at DESC;